import './globals.css';
import { Lato } from 'next/font/google';

const mont = Lato({
  subsets: ['latin'],
  style: ['normal', 'italic'],
  weight: ['100', '300', '400', '700', '900'],
  display: 'swap',
});

export const metadata = {
  title: 'Basi App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mont.className}>{children}</body>
    </html>
  );
}
